<h1 align="center">
    <img 
        src="../img/logo_white_bg.jpeg" 
        width="200" 
        border="1" />
</h1>
<h1 align="center">
    <b>GenAISHAP</b>
</h1>
<h4 align="center">
    <i>Explanations for Generative AI, LLM-and-SLM-Based, Solutions</i> ⚡️
</h4>



Generative AI SHAP (GenAISHAP) is a python library that supports the creation of explanations to the metrics obtained for solutions based on LLMs (Large Language Models) or SLMs (Small Language Models). 

The previous notebook showed an example of how to create the **Input** for ***GenAISHAP***, which is a simple Pandas DataFrame with the evaluation dataset. A pandas Dataframe like the following was produced and stored as a JSON file:

<img src="../img/input_example.png" width="1200" />

> The column `user_input` will be used to refer to the user prompt, and the columns `faithfulness`, `context_precision` and `context_recall` will be used as metric columns since those columns are numerical.
>
> The other columns, `retrieved_contexts`, `response`, and `reference` are not needed for **GenAISHAP** but were required for the calculation of the metrics.

***GenAISHAP*** works as follows.  ***GenAISHAP*** will create regression models, which we call them **black-box models**, for each of the metrics and will use those black-box models to produce explanations for each metric. The models are created from features extracted from the provided questions. Those **question features** could be generated automatically, using a tool, named **Featurizer** incorporated in the library or they can be manually created.

This notebook explains how to use the **Featurizer** tool.

In [1]:
import pandas as pd
from genaishap import Featurizer
from dotenv import load_dotenv

# 1. Load input and set environment variables

The **Featurizer** tool uses an LLM to produce the features and its corresponding values per instance sample. That is the reason we need to load the environment variable here in this notebook.  The loaded dataset is the one was created in the previous notebook.

In [2]:
load_dotenv()

True

In [3]:
df_test_dataset = pd.read_json('./test-dataset.json', orient='records')
df_test_dataset

,user_input,retrieved_contexts,response,reference,faithfulness,context_precision,context_recall
0,Can you provide for me the three highlights fo...,"[31. In 2018, to align with industry best prac...",The three highlights for the GHG emissions sec...,"Sure, they are: \n1. 65% cumulative GHG emissi...",1.000000,0.0,0.000000
1,What percentage of waste from Google's offices...,[Performance highlights\nThe following section...,The percentage of waste from Google's offices ...,Sixty-four percent.,1.000000,0.0,0.000000
2,Can you present me with the performance highli...,"[Education\nFor more than 40 years, we’ve work...",The performance highlights for empowering user...,Sure! The Performance Highlights for Empowerin...,1.000000,0.0,0.000000
3,What was the listed key achievement regarding ...,[Our approach\nWe believe that every business ...,There is no listed key achievement for Google ...,"In 2017, Google became the first major company...",1.000000,1.0,1.000000
4,Did Google reach its intended Waste target und...,[BUILDING BETTER DEVICES AND SERVICES\nTarget ...,"Yes, in 2021, Google achieved the Waste target...","No, this target has not been met in 2021. Howe...",0.500000,1.0,0.500000
5,How many EV charging locations were there on G...,[This guidance does not recognize existing ren...,The provided information does not specify the ...,200000,1.000000,0.0,0.000000
6,On what page of the report can I find the perf...,"[Employee Recruitment, Inclusion and Performan...",The performance highlights for the Empowering ...,The performance highlights for Empowering User...,1.000000,0.0,0.000000
7,Can you please provide for me the glossary of ...,[GRI INDEX\nGRI 304 - Biodiversity\nGRI 103 Ma...,The provided information does not include a gl...,"Sure, here is the glossary:\nGlossary\nCFE: ca...",0.000000,0.0,0.000000
8,On what page can I find details about Amazons ...,[IntroductionSustainability\nDriving Climate S...,Details about Amazon's climate solutions can b...,You can find information on driving climate so...,0.000000,0.0,0.000000
9,"For the listed Renewable Energy goals, by when...",[IntroductionSustainability\nDriving Climate S...,Amazon intends to have all operations powered ...,Amazon set the goal of becoming powered by 100...,1.000000,0.5,0.000000
10,Can you provide the Actions taken by Amazon fo...,[IntroductionSustainability\nDriving Climate S...,Amazon has taken several actions to achieve it...,"Sure, here they are:\nActions\n90% Electricity...",1.000000,1.0,0.000000
11,What were Amazon's Carbon Intesity values in (...,[IntroductionSustainability\nDriving Climate S...,Amazon's Carbon Intensity values (grams of CO2...,"Sure, here they are:\n2019: 122.8\n2020: 102.7...",1.000000,1.0,1.000000
12,What were Amazon's Total Carbon Footprint (MMT...,[IntroductionSustainability\nDriving Climate S...,Amazon's Total Carbon Footprint (MMT CO2e) for...,Amazon's total footprint for the years 2019-20...,1.000000,1.0,1.000000
13,On what page can of the report can I find info...,[Tackling Climate \nMisinformation\n \nClimat...,"The report does not mention ""The Climate Page ...",On page 14,0.666667,0.0,0.000000
14,What household brands were featured in the in ...,[Customer Shopping Experience\nWe have enabled...,The provided information does not include deta...,"Microsoft, jetBlue, Uber, Mercedez-Benz, Visa,...",1.000000,0.0,0.000000
15,What percentage of corporate emissions since 2...,[IntroductionSustainability\nDriving Climate S...,"Since 2020, 100% of the electricity used to po...",100% since April 2020.,0.000000,0.5,0.000000
16,"In Apple's comprehensive carbon footprint, wha...",[Gross emissions\n \nAvoided emissions\n \n...,The top two categories leading to the most avo...,The top two categories were: supplier clean en...,1.000000,1.0,1.000000
17,By what percentage did Apple reduce plastic in...,"[Across our business, we released eight \nprod...",Apple reduced plastic in packaging by 75 perce...,75%,1.000000,0.5,1.000000
18,How many metric tons of waste were redirected ...,[Current\nyear\nBase\nyear\nTarget\nDiversion ...,The provided information does not specify the ...,More than 2 million metric tons of waste were ...,1.000000,0.0,0.000000
19,"In 2021, how many hours were spent by staff ac...",[Growth and development\nWe want everyone to f...,"In 2021, staff spent more than 175,000 hours p...",175000 hours,1.000000,1.0,1.000000
20,How many millions of gallons of freshwater was...,[FY21 FY20 FY22\nCurrent yearBase year\n0M\n2M...,The provided information does not include data...,7600 million gallons of freshwater were saved ...,1.000000,0.0,0.000000
21,What were the Total Packaging resources used i...,[IntroductionSustainability\nReducing Packagin...,The provided information does not include data...,2021: 257000\n2020: 226000\n2019: 189000\n2018...,0.333333,0.0,0.000000
22,What is the objective of the Carbon Call initi...,"[In 2022, we also released a preview version o...",The objective of the Carbon Call initiative is...,The objective of Carbon Call is to unify the w...,1.000000,1.0,1.000000
23,What are the three key areas that will enable ...,[What’s next \nScope 3 emissions reduction \nM...,The three key areas that will enable the scale...,1 Advancing AI solutions for greater climate i...,1.000000,0.0,0.666667
24,How many people in India did Microsoft provide...,"[Chile\nSouth Africa\n16,408 \nBrazil\n340 \n...","Microsoft provided water access to 225,389 peo...","309,921",0.000000,0.0,0.000000
25,How many people in Indonesia did Microsoft pro...,"[Chile\nSouth Africa\n16,408 \nBrazil\n340 \n...",The specific number of people in Indonesia pro...,"225,389",1.000000,0.0,0.000000
26,How many people in Brazil did Microsoft provid...,"[Chile\nSouth Africa\n16,408 \nBrazil\n340 \n...","Microsoft provided water access to 552,058 peo...","16,408",1.000000,1.0,0.000000
27,How many people in Mexico did Microsoft provid...,[Improving access \nto water \nWe continue to ...,"Microsoft provided water access to 309,921 peo...",340,0.000000,0.0,1.000000
28,How many more acres of land does Microsoft nee...,[• • \na \n47\n | | | \nCommitments and progre...,"According to Ecosystems Chart 1, Microsoft has...",4998 more acres,0.600000,1.0,1.000000
29,What key insight was listed in page 56 of the ...,[Leadership About Highlights How We Operate Wh...,The context provided does not include informat...,25%\nWe are reducing idle power consumption of...,1.000000,0.0,0.000000
30,What key insight was listed in page 61 of the ...,[Leadership About Highlights How We Operate Wh...,The context provided does not include any info...,100%\nOur key European and American distributi...,1.000000,0.0,0.000000
31,What are the four commitments listed on page 66?,[UN Sustainable Development Goal Apple’s suppo...,The four commitments listed on page 66 are: \...,1. Using our voice on climate-related public p...,0.250000,0.0,0.000000
32,What is the last Key project listed under Poli...,"[Sometimes, that means joining \nregional coll...",The last key project listed under the Policy a...,"Making green jobs, skills, and entrepreneurshi...",0.500000,0.0,0.000000
33,"What are the sub sections for ""What We Create""...",[OUR APPROACH TO SUSTAINABILITY\nFor a Better ...,"The sub-sections for the ""What We Create"" sect...","Raising Awareness, Tackling Climate Misinforma...",0.888889,0.0,0.000000
34,What are the category labels for each topic in...,[Introduction Sustainability People Appendix \...,The context does not provide information about...,"Important, Very Important, Critical",1.000000,0.0,0.000000
35,How many pages and groups were removed for rep...,[UNITED NATIONS SUSTAINABLE DEVELOPMENT GOALS\...,"3,000 pages and groups were removed for repeat...",3000,0.000000,1.0,1.000000
36,How many artifacts were removed from Facebook ...,[UNITED NATIONS SUSTAINABLE DEVELOPMENT GOALS\...,Over 12 million pieces of misleading COVID-19 ...,12000000,1.000000,1.0,1.000000
37,How many unique visitors to the Facebook Marke...,[UNITED NATIONS SUSTAINABLE DEVELOPMENT GOALS\...,"There were 368,000 unique visitors to the Face...",368000,1.000000,1.0,1.000000
38,How many users were surveyed for their views o...,[TACKLING CLIMATE MISINFORMATION\n“Misinformat...,The provided information does not specify the ...,76328 users across 31 countries.,1.000000,0.0,0.000000
39,What were the subsections for the 2021 Highlig...,[2021 Highlights\nCelebrating today.\nWorking ...,The subsections for the 2021 Highlights were: ...,1 Protecting People and Planet Through Respons...,1.000000,0.0,0.000000
40,What are the subsections of the Workplaces sec...,[Employees have several feedback routes. While...,The subsections of the Workplaces section of t...,1. Healthy and Sustainable Workplaces\n2. Offi...,0.857143,0.0,0.000000
41,What is the fact about Oceans shared on page 43?,[PUSHPIN FACTS\nFACT SOURCE LINK\nEarly warnin...,The fact about oceans shared is that they abso...,Oceans absorb more than 90% ofthe heat that re...,0.500000,1.0,1.000000
42,What are the 4 facts shared in the Greenhouse ...,[18Netflix ESG Report 2022\n2022 SCOPE 1 AND 2...,The context does not provide specific facts la...,1. CO2 emissions are increasing more than 250 ...,0.875000,0.0,0.000000
43,"In the about netflix page, what are the mentio...",[3Netflix ESG Report 2022\nA letter from our c...,The mentioned highlights about the company inc...,Public in 2002\nFounded in 1997\n231M paid mem...,1.000000,0.0,0.000000
44,Who provided the testimonial on Netflix's Sust...,[24Netflix ESG Report 2022\nThe film and telev...,The provided context does not include any test...,"Christiana Figueres,\nDiplomat and Architect o...",1.000000,0.0,0.000000
45,What are the Scope 1 and Scope 2 emission redu...,[What’s next \nScope 3 emissions reduction \nM...,The Scope 1 and Scope 2 emission reduction lev...,1 Energy Efficiency\n2 Renewable Energy (elect...,1.000000,0.0,0.250000
46,Who provided the testimonial on Netflix's Sust...,[24Netflix ESG Report 2022\nThe film and telev...,The provided context does not include a testim...,"Elizabeth Sturcken,\nManaging Director, Enviro...",1.000000,0.0,0.000000
47,Can you provide the quote by Xiye Bastida?,[49Netflix ESG Report 2022\nAs a women-led B-C...,The provided context does not include a quote ...,Young people like myself view Netflix as a che...,1.000000,0.0,0.000000
48,Can you provide the quote by Aditi Sharma?,"[Employee Recruitment, Inclusion and Performan...",The provided context does not include a quote ...,"Through the Take Ten program, I got to learn a...",1.000000,0.0,0.000000
49,What 3 partner companies were spotlighted in t...,[Introduct ion Sustainability People \nIncreas...,The provided information does not mention any ...,1. Black Economic Development Fund\n2. Hope Cr...,1.000000,0.0,0.000000

The following code initializes the **Featurizer** with the data loaded in the previous step

In [4]:
featurizer = Featurizer.from_pandas(df_test_dataset)

# 2. Create features automatically

The following code uses an Azure OpenAI LLM deployment to create the features, by default the number of features is 12, but this number can be modified if required. If the quality of the black-box models is low, one option to improve it is to increase the number of features generated.

The features automatically generated can be or **boolean** or **list of strings**. The goal is to be able to capture the characteristics of the different user queries in a way that can be easily interpretable by a human, and at the same time these features should be able to be engineered to be used as regressors for the black-box regression models.  

The following is an example of how to create the features, and how to visualize them.

In [5]:
%%time

featurizer.create_features_using_azure_openai(
    deployment_name="gpt-4o", # Update with the name of your Azure OpenAI LLM deployment name
    num_features=25
)
print(featurizer.features.model_dump_json(indent=4))

{
    "features": [
        {
            "feature": "there_is_any_company_identified_in_the_question",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_companies_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "there_is_any_year_identified_in_the_question",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_years_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "there_is_any_page_number_identified_in_the_question",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_page_numbers_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_environmental_metrics",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_environmental_metrics_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_social_impact",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_social_impact_topics_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_corporate_goals",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_corporate_goals_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_specific_initiatives",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_initiatives_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_comparative_data",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_comparative_data_points_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_highlights_or_summaries",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_highlights_or_summaries_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_testimonials_or_quotes",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_testimonials_or_quotes_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_specific_locations",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_locations_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_specific_charts_or_graphs",
            "ftype": "boolean"
        },
        {
            "feature": "list_of_charts_or_graphs_identified_in_the_question",
            "ftype": "list_of_strings"
        },
        {
            "feature": "is_a_question_about_policy_or_advocacy",
            "ftype": "boolean"
        }
    ]
}
CPU times: user 124 ms, sys: 12.1 ms, total: 137 ms
Wall time: 7.61 s

These automatically generated features can be modified if required. For this, just use the `featurizer.features.features` list to remove or add features. For example, to remove the second question (index = 1), you can use `del` as follows:

```python
del featurizer.features.features[1]
```

To add an additional feature, you can use `append` as follows:

```python
from genaishap import Feature

featurizer.features.features.append(
    Feature(
        feature="is_an_open_ended_question",
        ftype="boolean"
    )
)
```

# 3. Fill out the features automatically

Once the list of features is created it is possible to automatically fill out the values of each feature using the **Featurizer**. The **Featurizer** uses an Azure OpenAI LLM to do the job. The batch size parameter is used to fill out batches of, for example, 5 questions. The batch size helps to control the number of tokens used per LLM call.

In [6]:
%%time

featurizer.fill_out_features_using_azure_openai(
    deployment_name="gpt-4o", 
    batch_size=5
)

  0%|          | 0/10 [00:00<?, ?it/s]

CPU times: user 404 ms, sys: 50.7 ms, total: 455 ms
Wall time: 43 s

In [7]:
df_features = featurizer.to_pandas()
df_features.style.set_table_styles(
    [{'selector': 'th', 'props': [('font-size', '5pt')]}]
).set_properties(**{'font-size': '8pt',})

It is possible to manually edit the values of the features or add or remove manually an entire column.  The easies way to do it is just to manipulate the `df_features` dataframe.  Unsing pandas Dataframe methods and functions it is easy to manipulate this table as required.  The following are the restrictions for the manual manipulation:
- The total number of records of `df_features` has to be the same as the number of records of `df_test_dataset`.
- The column names of `df_features` should be self explanatory since they are going to be used for the explanations.
- The type of the columns in `df_features` needs to be **boolean** or **list of strings**.

# 4. Store features and values as JSON file

In [8]:
df_features.to_json('./test-features.json', orient='records', indent=4)

Just for visualization, the following cell shows in a single table all the columns calculated so far, user input, metrics and question features

In [9]:
df_test_dataset.join(df_features)

,user_input,retrieved_contexts,response,reference,faithfulness,context_precision,context_recall,there_is_any_company_identified_in_the_question,list_of_companies_identified_in_the_question,there_is_any_year_identified_in_the_question,...,list_of_comparative_data_points_identified_in_the_question,is_a_question_about_highlights_or_summaries,list_of_highlights_or_summaries_identified_in_the_question,is_a_question_about_testimonials_or_quotes,list_of_testimonials_or_quotes_identified_in_the_question,is_a_question_about_specific_locations,list_of_locations_identified_in_the_question,is_a_question_about_specific_charts_or_graphs,list_of_charts_or_graphs_identified_in_the_question,is_a_question_about_policy_or_advocacy
0,Can you provide for me the three highlights fo...,"[31. In 2018, to align with industry best prac...",The three highlights for the GHG emissions sec...,"Sure, they are: \n1. 65% cumulative GHG emissi...",1.000000,0.0,0.000000,False,[],False,...,[],True,[Performance Highlights],False,[],False,[],False,[],False
1,What percentage of waste from Google's offices...,[Performance highlights\nThe following section...,The percentage of waste from Google's offices ...,Sixty-four percent.,1.000000,0.0,0.000000,True,[Google],True,...,[percentage of waste],False,[],False,[],True,[Google's offices globally],False,[],False
2,Can you present me with the performance highli...,"[Education\nFor more than 40 years, we’ve work...",The performance highlights for empowering user...,Sure! The Performance Highlights for Empowerin...,1.000000,0.0,0.000000,False,[],False,...,[],True,[performance highlights],False,[],False,[],False,[],False
3,What was the listed key achievement regarding ...,[Our approach\nWe believe that every business ...,There is no listed key achievement for Google ...,"In 2017, Google became the first major company...",1.000000,1.0,1.000000,True,[Google],True,...,[],False,[],False,[],False,[],False,[],False
4,Did Google reach its intended Waste target und...,[BUILDING BETTER DEVICES AND SERVICES\nTarget ...,"Yes, in 2021, Google achieved the Waste target...","No, this target has not been met in 2021. Howe...",0.500000,1.0,0.500000,True,[Google],True,...,[],False,[],False,[],False,[],False,[],False
5,How many EV charging locations were there on G...,[This guidance does not recognize existing ren...,The provided information does not specify the ...,200000,1.000000,0.0,0.000000,True,[Google],True,...,[],False,[],False,[],True,[Google Maps],False,[],False
6,On what page of the report can I find the perf...,"[Employee Recruitment, Inclusion and Performan...",The performance highlights for the Empowering ...,The performance highlights for Empowering User...,1.000000,0.0,0.000000,False,[],False,...,[],True,[performance highlights],False,[],False,[],False,[],False
7,Can you please provide for me the glossary of ...,[GRI INDEX\nGRI 304 - Biodiversity\nGRI 103 Ma...,The provided information does not include a gl...,"Sure, here is the glossary:\nGlossary\nCFE: ca...",0.000000,0.0,0.000000,False,[],False,...,[],True,[glossary],False,[],False,[],False,[],False
8,On what page can I find details about Amazons ...,[IntroductionSustainability\nDriving Climate S...,Details about Amazon's climate solutions can b...,You can find information on driving climate so...,0.000000,0.0,0.000000,True,[Amazon],False,...,[],False,[],False,[],False,[],False,[],False
9,"For the listed Renewable Energy goals, by when...",[IntroductionSustainability\nDriving Climate S...,Amazon intends to have all operations powered ...,Amazon set the goal of becoming powered by 100...,1.000000,0.5,0.000000,True,[Amazon],False,...,[],False,[],False,[],False,[],False,[],False
10,Can you provide the Actions taken by Amazon fo...,[IntroductionSustainability\nDriving Climate S...,Amazon has taken several actions to achieve it...,"Sure, here they are:\nActions\n90% Electricity...",1.000000,1.0,0.000000,True,[Amazon],False,...,[],False,[],False,[],False,[],False,[],False
11,What were Amazon's Carbon Intesity values in (...,[IntroductionSustainability\nDriving Climate S...,Amazon's Carbon Intensity values (grams of CO2...,"Sure, here they are:\n2019: 122.8\n2020: 102.7...",1.000000,1.0,1.000000,True,[Amazon],True,...,[C02e per $ of GMS],False,[],False,[],False,[],False,[],False
12,What were Amazon's Total Carbon Footprint (MMT...,[IntroductionSustainability\nDriving Climate S...,Amazon's Total Carbon Footprint (MMT CO2e) for...,Amazon's total footprint for the years 2019-20...,1.000000,1.0,1.000000,True,[Amazon],True,...,[MMT CO2e],False,[],False,[],False,[],False,[],False
13,On what page can of the report can I find info...,[Tackling Climate \nMisinformation\n \nClimat...,"The report does not mention ""The Climate Page ...",On page 14,0.666667,0.0,0.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
14,What household brands were featured in the in ...,[Customer Shopping Experience\nWe have enabled...,The provided information does not include deta...,"Microsoft, jetBlue, Uber, Mercedez-Benz, Visa,...",1.000000,0.0,0.000000,False,[],False,...,[],True,[climate pledge infographic],False,[],False,[],False,[],False
15,What percentage of corporate emissions since 2...,[IntroductionSustainability\nDriving Climate S...,"Since 2020, 100% of the electricity used to po...",100% since April 2020.,0.000000,0.5,0.000000,False,[],True,...,[],False,[],False,[],False,[],False,[],False
16,"In Apple's comprehensive carbon footprint, wha...",[Gross emissions\n \nAvoided emissions\n \n...,The top two categories leading to the most avo...,The top two categories were: supplier clean en...,1.000000,1.0,1.000000,True,[Apple],False,...,[],False,[],False,[],False,[],False,[],False
17,By what percentage did Apple reduce plastic in...,"[Across our business, we released eight \nprod...",Apple reduced plastic in packaging by 75 perce...,75%,1.000000,0.5,1.000000,True,[Apple],True,...,[2015],False,[],False,[],False,[],False,[],False
18,How many metric tons of waste were redirected ...,[Current\nyear\nBase\nyear\nTarget\nDiversion ...,The provided information does not specify the ...,More than 2 million metric tons of waste were ...,1.000000,0.0,0.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
19,"In 2021, how many hours were spent by staff ac...",[Growth and development\nWe want everyone to f...,"In 2021, staff spent more than 175,000 hours p...",175000 hours,1.000000,1.0,1.000000,True,[Apple],True,...,[],False,[],False,[],False,[],False,[],False
20,How many millions of gallons of freshwater was...,[FY21 FY20 FY22\nCurrent yearBase year\n0M\n2M...,The provided information does not include data...,7600 million gallons of freshwater were saved ...,1.000000,0.0,0.000000,False,[],True,...,[],False,[],False,[],False,[],False,[],False
21,What were the Total Packaging resources used i...,[IntroductionSustainability\nReducing Packagin...,The provided information does not include data...,2021: 257000\n2020: 226000\n2019: 189000\n2018...,0.333333,0.0,0.000000,False,[],True,...,"[2017, 2018, 2019, 2020, 2021]",False,[],False,[],False,[],False,[],False
22,What is the objective of the Carbon Call initi...,"[In 2022, we also released a preview version o...",The objective of the Carbon Call initiative is...,The objective of Carbon Call is to unify the w...,1.000000,1.0,1.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
23,What are the three key areas that will enable ...,[What’s next \nScope 3 emissions reduction \nM...,The three key areas that will enable the scale...,1 Advancing AI solutions for greater climate i...,1.000000,0.0,0.666667,False,[],False,...,[],False,[],False,[],False,[],False,[],False
24,How many people in India did Microsoft provide...,"[Chile\nSouth Africa\n16,408 \nBrazil\n340 \n...","Microsoft provided water access to 225,389 peo...","309,921",0.000000,0.0,0.000000,True,[Microsoft],False,...,[],False,[],False,[],True,[India],False,[],False
25,How many people in Indonesia did Microsoft pro...,"[Chile\nSouth Africa\n16,408 \nBrazil\n340 \n...",The specific number of people in Indonesia pro...,"225,389",1.000000,0.0,0.000000,True,[Microsoft],False,...,[],False,[],False,[],True,[Indonesia],False,[],False
26,How many people in Brazil did Microsoft provid...,"[Chile\nSouth Africa\n16,408 \nBrazil\n340 \n...","Microsoft provided water access to 552,058 peo...","16,408",1.000000,1.0,0.000000,True,[Microsoft],False,...,[],False,[],False,[],True,[Brazil],False,[],False
27,How many people in Mexico did Microsoft provid...,[Improving access \nto water \nWe continue to ...,"Microsoft provided water access to 309,921 peo...",340,0.000000,0.0,1.000000,True,[Microsoft],False,...,[],False,[],False,[],True,[Mexico],False,[],False
28,How many more acres of land does Microsoft nee...,[• • \na \n47\n | | | \nCommitments and progre...,"According to Ecosystems Chart 1, Microsoft has...",4998 more acres,0.600000,1.0,1.000000,True,[Microsoft],True,...,[],False,[],False,[],False,[],True,[Ecosystems Chart 1],False
29,What key insight was listed in page 56 of the ...,[Leadership About Highlights How We Operate Wh...,The context provided does not include informat...,25%\nWe are reducing idle power consumption of...,1.000000,0.0,0.000000,False,[],False,...,[],True,[key insight],False,[],False,[],False,[],False
30,What key insight was listed in page 61 of the ...,[Leadership About Highlights How We Operate Wh...,The context provided does not include any info...,100%\nOur key European and American distributi...,1.000000,0.0,0.000000,False,[],False,...,[],True,[key insight],False,[],False,[],False,[],False
31,What are the four commitments listed on page 66?,[UN Sustainable Development Goal Apple’s suppo...,The four commitments listed on page 66 are: \...,1. Using our voice on climate-related public p...,0.250000,0.0,0.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
32,What is the last Key project listed under Poli...,"[Sometimes, that means joining \nregional coll...",The last key project listed under the Policy a...,"Making green jobs, skills, and entrepreneurshi...",0.500000,0.0,0.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],True
33,"What are the sub sections for ""What We Create""...",[OUR APPROACH TO SUSTAINABILITY\nFor a Better ...,"The sub-sections for the ""What We Create"" sect...","Raising Awareness, Tackling Climate Misinforma...",0.888889,0.0,0.000000,False,[],False,...,[],True,[sub sections],False,[],False,[],False,[],False
34,What are the category labels for each topic in...,[Introduction Sustainability People Appendix \...,The context does not provide information about...,"Important, Very Important, Critical",1.000000,0.0,0.000000,False,[],False,...,[category labels],False,[],False,[],False,[],True,[chart],False
35,How many pages and groups were removed for rep...,[UNITED NATIONS SUSTAINABLE DEVELOPMENT GOALS\...,"3,000 pages and groups were removed for repeat...",3000,0.000000,1.0,1.000000,True,[Meta],False,...,[],False,[],False,[],False,[],False,[],True
36,How many artifacts were removed from Facebook ...,[UNITED NATIONS SUSTAINABLE DEVELOPMENT GOALS\...,Over 12 million pieces of misleading COVID-19 ...,12000000,1.000000,1.0,1.000000,True,[Facebook],False,...,[],False,[],False,[],False,[],False,[],True
37,How many unique visitors to the Facebook Marke...,[UNITED NATIONS SUSTAINABLE DEVELOPMENT GOALS\...,"There were 368,000 unique visitors to the Face...",368000,1.000000,1.0,1.000000,True,[Facebook],False,...,[],False,[],False,[],False,[],False,[],False
38,How many users were surveyed for their views o...,[TACKLING CLIMATE MISINFORMATION\n“Misinformat...,The provided information does not specify the ...,76328 users across 31 countries.,1.000000,0.0,0.000000,False,[],False,...,[countries],False,[],False,[],True,[countries],False,[],False
39,What were the subsections for the 2021 Highlig...,[2021 Highlights\nCelebrating today.\nWorking ...,The subsections for the 2021 Highlights were: ...,1 Protecting People and Planet Through Respons...,1.000000,0.0,0.000000,False,[],True,...,[],True,[2021 Highlights],False,[],False,[],False,[],False
40,What are the subsections of the Workplaces sec...,[Employees have several feedback routes. While...,The subsections of the Workplaces section of t...,1. Healthy and Sustainable Workplaces\n2. Offi...,0.857143,0.0,0.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
41,What is the fact about Oceans shared on page 43?,[PUSHPIN FACTS\nFACT SOURCE LINK\nEarly warnin...,The fact about oceans shared is that they abso...,Oceans absorb more than 90% ofthe heat that re...,0.500000,1.0,1.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
42,What are the 4 facts shared in the Greenhouse ...,[18Netflix ESG Report 2022\n2022 SCOPE 1 AND 2...,The context does not provide specific facts la...,1. CO2 emissions are increasing more than 250 ...,0.875000,0.0,0.000000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
43,"In the about netflix page, what are the mentio...",[3Netflix ESG Report 2022\nA letter from our c...,The mentioned highlights about the company inc...,Public in 2002\nFounded in 1997\n231M paid mem...,1.000000,0.0,0.000000,True,[Netflix],False,...,[],True,[highlights about the company],False,[],False,[],False,[],False
44,Who provided the testimonial on Netflix's Sust...,[24Netflix ESG Report 2022\nThe film and telev...,The provided context does not include any test...,"Christiana Figueres,\nDiplomat and Architect o...",1.000000,0.0,0.000000,True,[Netflix],False,...,[],False,[],True,[Netflix's Sustainability Strategy is music to...,False,[],False,[],False
45,What are the Scope 1 and Scope 2 emission redu...,[What’s next \nScope 3 emissions reduction \nM...,The Scope 1 and Scope 2 emission reduction lev...,1 Energy Efficiency\n2 Renewable Energy (elect...,1.000000,0.0,0.250000,False,[],False,...,[],False,[],False,[],False,[],False,[],False
46,Who provided the testimonial on Netflix's Sust...,[24Netflix ESG Report 2022\nThe film and telev...,The provided context does not include a testim...,"Elizabeth Sturcken,\nManaging Director, Enviro...",1.000000,0.0,0.000000,True,[Netflix],False,...,[],False,[],True,[This is what industry leadership looks like...],False,[],False,[],False
47,Can you provide the quote by Xiye Bastida?,[49Netflix ESG Report 2022\nAs a women-led B-C...,The provided context does not include a quote ...,Young people like myself view Netflix as a che...,1.000000,0.0,0.000000,False,[],False,...,[],False,[],True,[quote by Xiye Bastida],False,[],False,[],False
48,Can you provide the quote by Aditi Sharma?,"[Employee Recruitment, Inclusion and Performan...",The provided context does not include a quote ...,"Through the Take Ten program, I got to learn a...",1.000000,0.0,0.000000,False,[],False,...,[],False,[],True,[quote by Aditi Sharma],False,[],False,[],False
49,What 3 partner companies were spotlighted in t...,[Introduct ion Sustainability People \nIncreas...,The provided information does not mention any ...,1. Black Economic Development Fund\n2. Hope Cr...,1.000000,0.0,0.000000,True,[partner companies],False,...,[],False,[],False,[],False,[],False,[],False